# Módulo 4

- Tarea 2: Optimización de modelos
- Fecha de entrega: 23 de mayo de 2026

## Teoría

1. ¿Cuál es la diferencia entre Tensorflow/Keras y Pytorch? ¿Qué modelos se pueden implementar en Pytorch?, ¿En qué situaciones es mejor implementar Keras y en qué momentos Pytorch?

Resp. 

- **Diferencia entre TensorFlow/Keras y PyTorch**: 

La distinción principal reside en el tipo de gráfico de computación: TensorFlow/Keras suele utilizar gráficos estáticos (declarativos) donde el modelo se define completamente antes de ejecutarse, mientras que PyTorch emplea gráficos dinámicos que se construyen en tiempo de ejecución, permitiendo cambios inmediatos en la lógica del modelo. Además, PyTorch se considera más "Pythonic" y flexible para depurar código en comparación con la naturaleza más estructurada de Keras.

- **Modelos que se pueden implementar en PyTorch**

En PyTorch es posible desarrollar una amplia variedad de modelos, tales como:

    - Perceptrones multicapa (MLP) para datos tabulares.
    - Redes Neuronales Convolucionales (CNN) para clasificación de imágenes y visión computacional.
    - Redes Neuronales Recurrentes (RNN), incluyendo unidades LSTM y GRU, para procesamiento de secuencias y lenguaje natural.
    - Autoencoders y Redes Generativas Antagónicas (GAN) para aprendizaje no supervisado y generativo.
    - Regresores y clasificadores binarios o multiclase.

- **Cuándo utilizar Keras o PyTorch**:

Implementar Keras es mejor cuando se busca simplicidad y rapidez en el desarrollo, especialmente para principiantes o en proyectos donde la prioridad es el despliegue estable en entornos de producción industriales. Implementar PyTorch es ideal para investigadores y entusiastas que necesitan flexibilidad extrema para experimentar con arquitecturas complejas, bucles personalizados o comportamientos dinámicos que cambian según los datos de entrada

2. Supongamos que tenemos una arquitectura de red de la siguiente forma:

-  Una capa de entrada input igual a 10. **Es el Input No hay parámetros**
-  Una capa densa de 16 neuronas regularizada con L2 y función de activación ReLU. **Son 16 (neuronas) x 10 (inputs) + 16 sesgos = 176 parámetros**
-  Una capa de batch normalization. **Son 2 parámetros entreneables y 2 no entrenables por neurona. Esto da un total de 32 Entrenables + 32 No entrebales = 64 parámetros**
-  Una capa dropout con parámetro de 0.4. **ni regularización ni dropout añade parámetros**
-  Una capa densa de 32 neuronas regularizada con L2 y funci ́on de activación ReLU. **Son 32 (neuronas) x 16 (inputs salidos de las neuronas) + 32 sesgos = 544 parámetros**
-  Una capa de batch normalization. **Son 2 parámetros entreneables y 2 no entrenables por neurona. Esto da un total de 64 Entrenables + 64 No entrebales = 128 parámetros**
-  Una capa dropout con parámetro de 0.5. **ni regularización ni dropout añade parámetros**
-  Una capa densa con 1 neurona y función de activación sigmoide. **Son 1 (neuronas) x 31 (inputs) + 1 sesgo = 33 parámetros**

Dado lo anterior, calcula paso a paso el n ́umero de parámetros que se van obteniendo.
¿Cuántos son entrenables?, ¿Cuántos son no entrenables?

Resp.

En total el número de parámetros son 945. 849 Entrenables (Pesos, Sesgos, Betas y  gammas) y 96 (Mu´s, Sigma´s).

3. En clase se ha dicho que comúnmente el número de neuronas es en potencias de 2 y van aumentando hasta cierto valor y luego vuelven a disminuir. Investiga cual es la
base de este tipo de construcción y a qué se debe.

Resp.

El diseño de capas en potencias de 2 y la progresión expansión-contracción busca maximizar la eficiencia del hardware y la capacidad de aprendizaje mientras se evita el sobreajuste.
Las potencias de 2 optimizan el uso de la memoria en las GPUs. La expansión inicial permite capturar patrones ricos y detallados en un espacio de mayor dimensión, mientras que la contracción posterior actúa como un filtro selectivo que condensa el conocimiento en abstracciones útiles para la predicción final.
En una CNN típica, el número de filtros puede empezar en 64 y duplicarse a 128 o 256 conforme la red se hace más profunda para capturar características complejas; sin embargo, al llegar a las capas finales "totalmente conectadas", el número de neuronas disminuye drásticamente hacia el número de clases objetivo (ej. 10 para dígitos MNIST).
En conclusión, esta construcción no es aleatoria, sino un equilibrio técnico entre la fuerza bruta computacional (potencias de 2) y la estrategia de aprendizaje (expandir para entender, contraer para decidir).





4. ¿Qué es la GPU?, ¿Para qué sirve?, ¿Cuál es su importancia en el deep learning?


Una GPU (Unidad de Procesamiento Gráfico, por sus siglas en inglés) es un componente de hardware especializado diseñado originalmente para aplicaciones gráficas y la renderización de videojuegos. A diferencia de la CPU tradicional, la GPU está optimizada para realizar muchas operaciones matemáticas simples en paralelo de forma extremadamente rápida.

*¿Para qué sirve la GPU?* Su función principal es el procesamiento de grandes bloques de datos de manera simultánea. Específicamente, las GPUs se encargan de:
Computación Paralela: Dividen tareas complejas en miles de hilos de ejecución más pequeños que corren al mismo tiempo.
Operaciones Matriciales: Son excepcionalmente eficientes en realizar multiplicaciones y divisiones de matrices, operaciones que son la base tanto de los gráficos 3D como de los cálculos en redes neuronales. Alto Ancho de Banda de Memoria: Están diseñadas para mover grandes cantidades de datos (parámetros y activaciones) hacia y desde la memoria de manera mucho más rápida que una CPU, lo cual es crítico cuando los datos no caben en la memoria caché estándar.

*Su importancia en el Deep Learning* La GPU es considerada el motor que impulsó el renacimiento del Deep Learning debido a los siguientes factores:
Velocidad de Entrenamiento: En el mundo real, el entrenamiento de redes complejas con grandes volúmenes de datos puede ser órdenes de magnitud más rápido en una GPU que en una CPU. Lo que en una CPU tomaría días o semanas, una GPU puede resolverlo en minutos u horas.
Soporte para Big Data: El auge del aprendizaje profundo a partir de 2012 no es coincidencia; se debió a que la tecnología de las GPUs se desarrolló lo suficiente como para satisfacer el hambre de datos de estos modelos.
Optimización de Algoritmos: Técnicas fundamentales como el descenso de gradiente por mini-batches aprovechan directamente la optimización de hardware de las GPUs para el cálculo matricial.
Flexibilidad (GP-GPUs): Con la llegada de lenguajes como CUDA de NVIDIA, las GPUs dejaron de ser solo para gráficos y se convirtieron en dispositivos de propósito general (GP-GPUs) capaces de ejecutar cualquier código de computación numérica, lo que las hace la plataforma ideal para frameworks como TensorFlow y PyTorch.
En conclusión, la GPU es vital porque proporciona la fuerza bruta computacional necesaria para manejar la profundidad de las redes modernas y la escala de los conjuntos de datos actuales, permitiendo avances que de otro modo serían computacionalmente imposibles

### Referencias

- Calin, O. (2020). Deep Learning Architectures: A Mathematical Approach. Springer Nature Switzerland AG.

- Gallatin, K., & Albon, C. (2023). Machine Learning with Python Cookbook: Practical Solutions from Preprocessing to Deep Learning (2.ª ed.). O'Reilly Media, Inc.

- Géron, A. (2023). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow: Concepts, Tools, and Techniques to Build Intelligent Systems (3.ª ed.). O'Reilly Media, Inc.

- Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.

- Ortega Ruiz, M. A. (2025). Introduction to Deep Learning. Toronto Academic Press

## Práctica

In [5]:
# Importar bibliotecas necesarias 

import pandas as pd

In [ ]:
# Cargamos el dataset especificando la columna de fecha
df = pd.read_csv('sample_trans.csv')

In [6]:
df.head()

,fecha_de_transaccion,canal_de_compra,division,sku_producto,cliente_unico_id,orden_de_venta,monto_bruto,monto_neto
0,7/30/2025 12:00:00 AM,Palacio de Hierro,JUGUETERIA,43828158,19c749a2322a9e0da8f648321c67f773,20250730_1013_342_5857,359.00,359.00
1,11/18/2024 12:00:00 AM,Palacio de Hierro,GOURMET,43814414,c490f3d2f25766657ffb0e756508786e,20241118_1009_421_756,587.00,587.00
2,9/3/2024 12:00:00 AM,E Commerce,DAMAS,43776264,e38923d6ba9d0402b4b0f67c550e54c8,Sites-palacio-MX-Site.5008756547,2190.00,1888.00
3,2/1/2025 12:00:00 AM,E Commerce,TECNOLOGIA,44115898,93ff5ba6316cb5cd8605f56b99c93b01,Sites-palacio-MX-Site.1010194069,13166.37,11350.32
4,12/29/2024 12:00:00 AM,Palacio de Hierro,DAMAS,43825319,3bc936faa076db40a2cbc5d2ffb8861e,20241229_1005_185_6514.0,3114.00,3114.00

In [7]:
# Convertimos la columna a tipo datetime real
df['fecha_de_transaccion'] = pd.to_datetime(
    df['fecha_de_transaccion'], 
    errors='coerce'
)

# Opcional: Si solo te importa la fecha y quieres deshacerte del "12:00:00 AM"
df['fecha_de_transaccion'] = df['fecha_de_transaccion'].dt.date

# Revisamos cómo quedó
print(df.head())
print(df.dtypes)

/var/folders/8v/p10964lx7y786kktss6jf6wc0000gn/T/ipykernel_32316/1292437467.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['fecha_de_transaccion'] = pd.to_datetime(

  fecha_de_transaccion    canal_de_compra    division sku_producto  \
0           2025-07-30  Palacio de Hierro  JUGUETERIA     43828158
1           2024-11-18  Palacio de Hierro     GOURMET     43814414
2           2024-09-03         E Commerce       DAMAS     43776264
3           2025-02-01         E Commerce  TECNOLOGIA     44115898
4           2024-12-29  Palacio de Hierro       DAMAS     43825319

                   cliente_unico_id                    orden_de_venta  \
0  19c749a2322a9e0da8f648321c67f773            20250730_1013_342_5857
1  c490f3d2f25766657ffb0e756508786e             20241118_1009_421_756
2  e38923d6ba9d0402b4b0f67c550e54c8  Sites-palacio-MX-Site.5008756547
3  93ff5ba6316cb5cd8605f56b99c93b01  Sites-palacio-MX-Site.1010194069
4  3bc936faa076db40a2cbc5d2ffb8861e          20241229_1005_185_6514.0

   monto_bruto  monto_neto
0       359.00      359.00
1       587.00      587.00
2      2190.00     1888.00
3     13166.37    11350.32
4      3114.00     3114.00
fecha_de_transaccion     object
canal_de_compra          object
division                 object
sku_producto             object
cliente_unico_id         object
orden_de_venta           object
monto_bruto             float64
monto_neto              float64
dtype: object

In [16]:
# Convertimos y aseguramos el tipo datetime64 de Pandas
df['fecha_de_transaccion'] = pd.to_datetime(df['fecha_de_transaccion'], errors='coerce')

# Verificamos de nuevo los tipos de datos
print(df['fecha_de_transaccion'].dtype)


# Span del dataset

df['fecha_de_transaccion'].min(), df['fecha_de_transaccion'].max()

datetime64[ns]

(Timestamp('2024-09-01 00:00:00'), Timestamp('2025-08-11 00:00:00'))

In [9]:
df.shape

(4101885, 8)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101885 entries, 0 to 4101884
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   fecha_de_transaccion  datetime64[ns]
 1   canal_de_compra       object
 2   division              object
 3   sku_producto          object
 4   cliente_unico_id      object
 5   orden_de_venta        object
 6   monto_bruto           float64
 7   monto_neto            float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 250.4+ MB

In [ ]:
# Valores Nulos por columna
df.isnull().sum()

fecha_de_transaccion        0
canal_de_compra          1019
division                64038
sku_producto                0
cliente_unico_id            0
orden_de_venta              0
monto_bruto                 0
monto_neto                  0
dtype: int64

In [11]:
df.describe()

                fecha_de_transaccion   monto_bruto    monto_neto
count                        4101885  4.101885e+06  4.101885e+06
mean   2025-01-29 10:03:48.375586816  3.038613e+03  2.906902e+03
min              2024-09-01 00:00:00 -8.500000e+06 -8.500000e+06
25%              2024-11-12 00:00:00  3.990000e+02  3.850000e+02
50%              2025-01-02 00:00:00  1.049000e+03  9.990000e+02
75%              2025-05-01 00:00:00  2.570000e+03  2.410340e+03
max              2025-08-11 00:00:00  7.350000e+06  7.350000e+06
std                              NaN  1.520356e+04  1.509125e+04

In [13]:
# 1. Estructura general y tipos de datos actuales
print("--- ESTRUCTURA Y TIPOS DE DATOS ---")
print(df.info())
print("\n" + "="*50 + "\n")

# 2. Conteo de Valores Nulos (Missing Values)
print("--- VALORES NULOS POR COLUMNA ---")
valores_nulos = df.isnull().sum()
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100
tabla_nulos = pd.DataFrame({'Total Nulos': valores_nulos, 'Porcentaje (%)': porcentaje_nulos})
print(tabla_nulos[tabla_nulos['Total Nulos'] > 0] if valores_nulos.sum() > 0 else "¡Increíble! No hay valores nulos.")
print("\n" + "="*50 + "\n")

# 3. Resumen Estadístico de Variables Numéricas
print("--- RESUMEN ESTADÍSTICO (monto_bruto y monto_neto) ---")
print(df.describe())
print("\n" + "="*50 + "\n")

# 4. Cardinalidad y Valores Únicos (Especialmente los IDs)
print("--- CARDINALIDAD DE VARIABLES CLAVE ---")
print(f"Total de registros en el dataset: {len(df)}")
print(f"Clientes únicos (cliente_unico_id): {df['cliente_unico_id'].nunique()}")
print(f"Órdenes de venta únicas (orden_de_venta): {df['orden_de_venta'].nunique()}")
print(f"SKUs únicos (sku_producto): {df['sku_producto'].nunique()}")
print(f"Divisiones comerciales: {df['division'].nunique()}")
print(f"Canales de compra: {df['canal_de_compra'].nunique()}")

--- ESTRUCTURA Y TIPOS DE DATOS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101885 entries, 0 to 4101884
Data columns (total 8 columns):
 #   Column                Dtype
---  ------                -----
 0   fecha_de_transaccion  datetime64[ns]
 1   canal_de_compra       object
 2   division              object
 3   sku_producto          object
 4   cliente_unico_id      object
 5   orden_de_venta        object
 6   monto_bruto           float64
 7   monto_neto            float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 250.4+ MB
None

==================================================

--- VALORES NULOS POR COLUMNA ---
                 Total Nulos  Porcentaje (%)
canal_de_compra         1019        0.024842
division               64038        1.561185

==================================================

--- RESUMEN ESTADÍSTICO (monto_bruto y monto_neto) ---
                fecha_de_transaccion   monto_bruto    monto_neto
count                        4101885  4.101885e+06  4.101885e+06
mean   2025-01-29 10:03:48.375586816  3.038613e+03  2.906902e+03
min              2024-09-01 00:00:00 -8.500000e+06 -8.500000e+06
25%              2024-11-12 00:00:00  3.990000e+02  3.850000e+02
50%              2025-01-02 00:00:00  1.049000e+03  9.990000e+02
75%              2025-05-01 00:00:00  2.570000e+03  2.410340e+03
max              2025-08-11 00:00:00  7.350000e+06  7.350000e+06
std                              NaN  1.520356e+04  1.509125e+04

==================================================

--- CARDINALIDAD DE VARIABLES CLAVE ---
Total de registros en el dataset: 4101885
Clientes únicos (cliente_unico_id): 770941
Órdenes de venta únicas (orden_de_venta): 3384732
SKUs únicos (sku_producto): 484289
Divisiones comerciales: 25
Canales de compra: 6

In [14]:
# 1. Análisis de montos negativos
negativos_bruto = (df['monto_bruto'] < 0).sum()
negativos_neto = (df['monto_neto'] < 0).sum()

# 2. Análisis de montos en cero (transacciones sin valor)
ceros_neto = (df['monto_neto'] == 0).sum()

# 3. Análisis de montos sospechosamente altos (Outliers superiores)
altos_50k = (df['monto_neto'] > 50000).sum()
altos_100k = (df['monto_neto'] > 100000).sum()
altos_1M = (df['monto_neto'] > 1000000).sum()

print("--- CONTEO DE ANOMALÍAS EN MONTOS ---")
print(f"Registros con Monto Bruto negativo: {negativos_bruto} ({negativos_bruto/len(df)*100:.4f}%)")
print(f"Registros con Monto Neto negativo: {negativos_neto} ({negativos_neto/len(df)*100:.4f}%)")
print(f"Registros con Monto Neto en cero ($0): {ceros_neto} ({ceros_neto/len(df)*100:.4f}%)")
print("\n--- DISTRIBUCIÓN DE OUTLIERS SUPERIORES (Monto Neto) ---")
print(f"Transacciones mayores a $50,000: {altos_50k} ({altos_50k/len(df)*100:.4f}%)")
print(f"Transacciones mayores a $100,000: {altos_100k} ({altos_100k/len(df)*100:.4f}%)")
print(f"Transacciones mayores a $1,000,000: {altos_1M} ({altos_1M/len(df)*100:.4f}%)")

--- CONTEO DE ANOMALÍAS EN MONTOS ---
Registros con Monto Bruto negativo: 73698 (1.7967%)
Registros con Monto Neto negativo: 73698 (1.7967%)
Registros con Monto Neto en cero ($0): 104902 (2.5574%)

--- DISTRIBUCIÓN DE OUTLIERS SUPERIORES (Monto Neto) ---
Transacciones mayores a $50,000: 20257 (0.4938%)
Transacciones mayores a $100,000: 6580 (0.1604%)
Transacciones mayores a $1,000,000: 53 (0.0013%)

In [15]:
import pandas as pd

# 1. Análisis Temporal (Transacciones por Año-Mes)
print("--- TRANSACCIONES POR MES ---")
transacciones_por_mes = df['fecha_de_transaccion'].dt.to_period('M').value_counts().sort_index()
print(transacciones_por_mes)
print("\n" + "="*50 + "\n")

# 2. Análisis de Canales de Compra (Incluyendo Nulos)
print("--- DISTRIBUCIÓN DE CANALES DE COMPRA ---")
print(df['canal_de_compra'].value_counts(dropna=False))
print("\n" + "="*50 + "\n")

# 3. Top 10 Divisiones Comerciales (Para ver dónde se concentra el negocio)
print("--- TOP 10 DIVISIONES ---")
print(df['division'].value_counts(dropna=False).head(10))
print("\n" + "="*50 + "\n")

# 4. Concentración de Clientes (¿Cuántas transacciones hace el cliente promedio?)
print("--- ESTADÍSTICAS DE TRANSACCIONES POR CLIENTE ---")
transacciones_por_cliente = df['cliente_unico_id'].value_counts()
print(transacciones_por_cliente.describe())

--- TRANSACCIONES POR MES ---
fecha_de_transaccion
2024-09    353497
2024-10    530284
2024-11    549251
2024-12    603595
2025-01    315345
2025-02    228148
2025-03    226929
2025-04    245117
2025-05    398733
2025-06    297495
2025-07    294804
2025-08     58687
Freq: M, Name: count, dtype: int64

==================================================

--- DISTRIBUCIÓN DE CANALES DE COMPRA ---
canal_de_compra
Palacio de Hierro    2546472
E Commerce           1316498
Boutiques             120829
La BPH                 56879
Outlets                51421
Casa Palacio            8767
NaN                     1019
Name: count, dtype: int64

==================================================

--- TOP 10 DIVISIONES ---
division
DAMAS                            557102
CABALLEROS                       463196
BOUTIQUES                        407076
BELLEZA                          379405
GOURMET                          322536
INFANTILES                       277487
HOGAR                            271935
TECNOLOGIA                       229474
RELOJERIA JOYERIA Y ESCRITURA    166927
MARCAS PROPIAS                   165929
Name: count, dtype: int64

==================================================

--- ESTADÍSTICAS DE TRANSACCIONES POR CLIENTE ---
count    770941.000000
mean          5.320621
std          18.156131
min           1.000000
25%           1.000000
50%           2.000000
75%           6.000000
max       13885.000000
Name: count, dtype: float64

## Feature Engineering

In [ ]:
df['descuento_aplicado'] = df['monto_bruto'] - df['monto_neto']

## División del Data Set

In [17]:
# Aseguramos que la columna sea datetime por si acaso
df['fecha_de_transaccion'] = pd.to_datetime(df['fecha_de_transaccion'])

# 1. Creamos el dataset para construir las variables (X)
df_historico = df[
    (df['fecha_de_transaccion'] >= '2024-09-01') & 
    (df['fecha_de_transaccion'] <= '2025-04-30')
].copy()

# 2. Creamos el dataset para construir la variable objetivo (Y)
df_futuro = df[
    (df['fecha_de_transaccion'] >= '2025-05-01') & 
    (df['fecha_de_transaccion'] <= '2025-07-31')
].copy()

# Validamos cuántas filas quedaron en cada uno
print(f"Filas en el histórico (Features): {df_historico.shape[0]}")
print(f"Filas en el futuro (Target): {df_futuro.shape[0]}")

Filas en el histórico (Features): 3052166
Filas en el futuro (Target): 991032

In [19]:
# Agrupamos por cliente y sumamos su monto neto del futuro
df_y = df_futuro.groupby('cliente_unico_id')['monto_neto'].sum().reset_index()

# Renombramos la columna correctamente usando True
df_y.rename(columns={'monto_neto': 'target_cltv'}, inplace=True)

# Revisamos cómo queda esta estructura
print(f"Total de clientes únicos que compraron en el periodo futuro: {df_y.shape[0]}")
print(df_y.head())

Total de clientes únicos que compraron en el periodo futuro: 352452
                   cliente_unico_id  target_cltv
0  000005f709693df2d048c8396c1e6162      4509.84
1  00009b78cda0aff32a2bf0dab56b5f76      4450.00
2  000159dc2b570c1ccd40b9247693ca76      4562.07
3  00015b468fcfa6fa3aeaeb15a7663e61      9228.00
4  00018b559f3e018dd37fbe181c9ef115      1199.00

## Feature Engineering de data set histórico

In [20]:
# Definimos la fecha de referencia (final del histórico)
fecha_referencia = pd.to_datetime('2025-05-01')

# Agrupamos el histórico por cliente
df_rfm = df_historico.groupby('cliente_unico_id').agg(
    # 1. Recencia: Días desde la última transacción hasta la fecha de referencia
    ultima_compra=('fecha_de_transaccion', 'max'),
    
    # 2. Frecuencia: Número de órdenes de venta únicas
    frecuencia=('orden_de_venta', 'nunique'),
    
    # 3. Monetario: Estadísticos del monto neto en el pasado
    monto_total_hist=('monto_neto', 'sum'),
    monto_max_hist=('monto_neto', 'max'),
    monto_medio_hist=('monto_neto', 'mean')
).reset_index()

# Calculamos los días exactos de recencia
df_rfm['recencia'] = (fecha_referencia - df_rfm['ultima_compra']).dt.days

# Ya no necesitamos la columna de la fecha máxima, la borramos para limpiar
df_rfm.drop(columns=['ultima_compra'], inplace=True)

# Revisamos cómo va quedando el dataset de características (X)
print(f"Total de clientes únicos identificados en el histórico: {df_rfm.shape[0]}")
print(df_rfm.head())

Total de clientes únicos identificados en el histórico: 658058
                   cliente_unico_id  frecuencia  monto_total_hist  \
0  000005d043269af46202a43748865e64           4          27747.00
1  000008fe7c2d1f99f5dae8afb4235c8c           1           1438.00
2  0000444fcca40a6242c5279210021108           1            585.86
3  00004cfade0c9f7a491c7472051a5673           1           2327.59
4  00007330e325bb763ecdb0690667d6b9           1           2319.00

   monto_max_hist  monto_medio_hist  recencia
0        24000.00           6936.75       234
1         1015.00            719.00        73
2          585.86            585.86       108
3         2327.59           2327.59        74
4         2319.00           2319.00       237

In [21]:
# 1. Creamos la tabla pivote de canales (llenando con 0 si no compró en ese canal)
df_canales_pivot = df_historico.pivot_table(
    index='cliente_unico_id',
    columns='canal_de_compra',
    values='monto_neto',
    aggfunc='sum',
    fill_value=0
).reset_index()

# 2. Renombramos las columnas para que sea claro que representan montos por canal
# Esto evita caracteres raros o espacios en los nombres de las columnas
df_canales_pivot.columns = [
    f'monto_canal_{str(col).replace(" ", "_").replace("NaN", "NULO")}' if col != 'cliente_unico_id' else col 
    for col in df_canales_pivot.columns
]

# 3. Revisamos cómo quedó este pivote antes de pegarlo a nuestro dataset principal
print(f"Dimensiones del pivote de canales: {df_canales_pivot.shape}")
print(df_canales_pivot.head())

Dimensiones del pivote de canales: (658003, 7)
                   cliente_unico_id  monto_canal_Boutiques  \
0  000005d043269af46202a43748865e64                    0.0
1  000008fe7c2d1f99f5dae8afb4235c8c                    0.0
2  0000444fcca40a6242c5279210021108                    0.0
3  00004cfade0c9f7a491c7472051a5673                    0.0
4  00007330e325bb763ecdb0690667d6b9                    0.0

   monto_canal_Casa_Palacio  monto_canal_E_Commerce  monto_canal_La_BPH  \
0                       0.0                 2269.00                 0.0
1                       0.0                    0.00                 0.0
2                       0.0                  585.86                 0.0
3                       0.0                 2327.59                 0.0
4                       0.0                 2319.00                 0.0

   monto_canal_Outlets  monto_canal_Palacio_de_Hierro
0                  0.0                        25478.0
1                  0.0                         1438.0
2                  0.0                            0.0
3                  0.0                            0.0
4                  0.0                            0.0

In [22]:
# 1. Creamos la tabla pivote de divisiones (llenando con 0 si no hay consumo)
df_divisiones_pivot = df_historico.pivot_table(
    index='cliente_unico_id',
    columns='division',
    values='monto_neto',
    aggfunc='sum',
    fill_value=0
).reset_index()

# 2. Limpiamos los nombres de las columnas para evitar espacios, diagonales o caracteres raros
# que suelen causar errores en XGBoost/LightGBM
df_divisiones_pivot.columns = [
    f'monto_div_{str(col).replace(" ", "_").replace("/", "_").replace("&", "y")}' if col != 'cliente_unico_id' else col 
    for col in df_divisiones_pivot.columns
]

# 3. Revisamos las dimensiones y un vistazo rápido
print(f"Dimensiones del pivote de divisiones: {df_divisiones_pivot.shape}")
print(df_divisiones_pivot.head(2))

Dimensiones del pivote de divisiones: (650727, 26)
                   cliente_unico_id  monto_div_BELLEZA  monto_div_BOUTIQUES  \
0  000005d043269af46202a43748865e64                0.0                999.0
1  000008fe7c2d1f99f5dae8afb4235c8c                0.0                  0.0

   monto_div_CABALLEROS  monto_div_CONCESIONARIOS  monto_div_DAMAS  \
0                2269.0                       0.0              0.0
1                   0.0                       0.0              0.0

   monto_div_DEPORTES  monto_div_GOURMET  monto_div_HOGAR  \
0                 0.0                0.0              0.0
1                 0.0                0.0           1438.0

   monto_div_INFANTILES  ...  monto_div_PROMOCIONES_ESPECIALES  \
0                   0.0  ...                               0.0
1                   0.0  ...                               0.0

   monto_div_RELOJERIA_JOYERIA_Y_ESCRITURA  \
0                                      0.0
1                                      0.0

   monto_div_SERVICIOS_AL_CLIENTE__HARDLINES  \
0                                        0.0
1                                        0.0

   monto_div_SERVICIOS_AL_CLIENTE_PH  monto_div_SERVICIOS_RESTAURANTES  \
0                                0.0                               0.0
1                                0.0                               0.0

   monto_div_SERVICIOS_SPA  monto_div_SERVICIOS_VARIOS  monto_div_TECNOLOGIA  \
0                      0.0                         0.0                   0.0
1                      0.0                         0.0                   0.0

   monto_div_TECNOLOGÍA  monto_div_TERCEROS_NO_OBJETO_DE_IVA
0                   0.0                                  0.0
1                   0.0                                  0.0

[2 rows x 26 columns]

In [23]:
# 1. Unimos el RFM básico con el pivote de canales
X_historico = pd.merge(df_rfm, df_canales_pivot, on='cliente_unico_id', how='left')

# 2. Unimos el resultado con el pivote de divisiones
X_historico = pd.merge(X_historico, df_divisiones_pivot, on='cliente_unico_id', how='left')

# 3. Llenamos los posibles valores vacíos (NaN) con 0 para que los modelos no fallen
X_historico.fillna(0, inplace=True)

# Validamos las dimensiones finales de nuestra matriz de entrada
print(f"Dimensiones finales de la matriz X: {X_historico.shape}")
print(f"¿Hay algún valor nulo remanente?: {X_historico.isnull().sum().sum()}")

Dimensiones finales de la matriz X: (658058, 37)
¿Hay algún valor nulo remanente?: 0

In [25]:
import pandas as pd

# 1. Unimos las características con la variable objetivo
df_modelo = pd.merge(X_historico, df_y, on='cliente_unico_id', how='left')

# 2. Los clientes que no compraron en el futuro tienen un CLTV de $0
df_modelo['target_cltv'].fillna(0, inplace=True)

# 3. Verificamos las dimensiones y la distribución del target
print(f"Dimensiones del dataset final de modelado: {df_modelo.shape}")
print("\n--- DISTRIBUCIÓN DE NUESTRO TARGET (CLTV) ---")
print(df_modelo['target_cltv'].describe())

Dimensiones del dataset final de modelado: (658058, 38)

--- DISTRIBUCIÓN DE NUESTRO TARGET (CLTV) ---
count    6.580580e+05
mean     3.306640e+03
std      4.560212e+04
min     -4.306870e+05
25%      0.000000e+00
50%      0.000000e+00
75%      1.670000e+03
max      3.151035e+07
Name: target_cltv, dtype: float64

In [26]:
# Vemos el valor en el percentil 99.5
limite_superior = df_modelo['target_cltv'].quantile(0.995)
print(f"El percentil 99.5% del target es: ${limite_superior:,.2f}")

El percentil 99.5% del target es: $72,689.05

In [27]:
import numpy as np

# 1. Aplicamos el piso en 0 para montos negativos
df_modelo['target_cltv'] = df_modelo['target_cltv'].clip(lower=0)

# 2. Aplicamos el techo en el percentil 99.5% ($72,689.05)
limite_superior = 72689.05
df_modelo['target_cltv'] = df_modelo['target_cltv'].clip(upper=limite_superior)

# 3. Verificamos cómo quedó la distribución final del target
print("--- DISTRIBUCIÓN FINAL DEL TARGET (LIMPIO) ---")
print(df_modelo['target_cltv'].describe())

--- DISTRIBUCIÓN FINAL DEL TARGET (LIMPIO) ---
count    658058.000000
mean       2731.086801
std        8221.858380
min           0.000000
25%           0.000000
50%           0.000000
75%        1670.000000
max       72689.050000
Name: target_cltv, dtype: float64

In [28]:
# 1. Definimos la lista de columnas que NO van a entrar al modelo
columnas_a_excluir = ['cliente_unico_id', 'target_cltv']

# 2. Creamos la matriz X (todas las columnas menos las excluidas)
X = df_modelo.drop(columns=columnas_a_excluir)

# 3. Creamos el vector Y (nuestro target)
y = df_modelo['target_cltv']

# Verificamos las formas finales
print(f"Dimensiones de la matriz de entrada X: {X.shape}")
print(f"Dimensiones del vector objetivo y: {y.shape}")
print(f"\nLista de variables independientes que usará el modelo ({X.shape[1]} en total):")
print(list(X.columns))

Dimensiones de la matriz de entrada X: (658058, 36)
Dimensiones del vector objetivo y: (658058,)

Lista de variables independientes que usará el modelo (36 en total):
['frecuencia', 'monto_total_hist', 'monto_max_hist', 'monto_medio_hist', 'recencia', 'monto_canal_Boutiques', 'monto_canal_Casa_Palacio', 'monto_canal_E_Commerce', 'monto_canal_La_BPH', 'monto_canal_Outlets', 'monto_canal_Palacio_de_Hierro', 'monto_div_BELLEZA', 'monto_div_BOUTIQUES', 'monto_div_CABALLEROS', 'monto_div_CONCESIONARIOS', 'monto_div_DAMAS', 'monto_div_DEPORTES', 'monto_div_GOURMET', 'monto_div_HOGAR', 'monto_div_INFANTILES', 'monto_div_JUGUETERIA', 'monto_div_LUJO_MODA', 'monto_div_MARCAS_PROPIAS', 'monto_div_NUEVOS_NEGOCIOS', 'monto_div_OUTLET', 'monto_div_PREPAGOS_Y_DEPOSITOS_NO_OBJETO_DE_IVA', 'monto_div_PROMOCIONES_ESPECIALES', 'monto_div_RELOJERIA_JOYERIA_Y_ESCRITURA', 'monto_div_SERVICIOS_AL_CLIENTE__HARDLINES', 'monto_div_SERVICIOS_AL_CLIENTE_PH', 'monto_div_SERVICIOS_RESTAURANTES', 'monto_div_SERVICIOS_SPA', 'monto_div_SERVICIOS_VARIOS', 'monto_div_TECNOLOGIA', 'monto_div_TECNOLOGÍA', 'monto_div_TERCEROS_NO_OBJETO_DE_IVA']

## Pre-Modelado

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split

# 1. Consolidamos la división de Tecnología en una sola columna si existen ambas
if 'monto_div_TECNOLOGÍA' in X.columns and 'monto_div_TECNOLOGIA' in X.columns:
    X['monto_div_TECNOLOGIA'] = X['monto_div_TECNOLOGIA'] + X['monto_div_TECNOLOGÍA']
    X.drop(columns=['monto_div_TECNOLOGÍA'], inplace=True)

# 2. Hacemos la partición de datos (80% entrenamiento, 20% prueba)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.2, 
    random_state=42
)

# Verificamos los tamaños resultantes
print("--- TAMAÑOS DE LAS PARTICIONES ---")
print(f"X_train (Entrenamiento): {X_train.shape}")
print(f"X_test (Prueba):        {X_test.shape}")

--- TAMAÑOS DE LAS PARTICIONES ---
X_train (Entrenamiento): (526446, 35)
X_test (Prueba):        (131612, 35)

In [30]:
from sklearn.preprocessing import RobustScaler

# 1. Inicializamos el escalador
scaler = RobustScaler()

# 2. Ajustamos el escalador con TRAIN y transformamos ambos
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("¡Datos escalados con éxito!")
print(f"Forma de X_train_scaled: {X_train_scaled.shape}")
print(f"Forma de X_test_scaled:  {X_test_scaled.shape}")

¡Datos escalados con éxito!
Forma de X_train_scaled: (526446, 35)
Forma de X_test_scaled:  (131612, 35)